//! Explicit, read-only source preview. Import commits reuse the normal guarded document command.
use super::{resolve_project, AppState};
use adashi_storage_api::markdown::MarkdownDesignDocument;
use adashi_storage_api::ProjectStorage;
use crate::storage::ProjectStore;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::Path;
use tauri::{AppHandle, State};
use tauri_plugin_dialog::DialogExt;

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(super) struct ImportSource { pub source_path: String, pub fingerprint: String }

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub(super) struct ImportPreview {
    source: ImportSource,
    document: MarkdownDesignDocument,
    duplicates: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn source_is_complete_and_preview_guard_detects_changes() {
        let root=tempfile::tempdir().unwrap();
        let path=root.path().join("design.md");
        let original="# Prose\r\n日本語 Grüße\r\n```rust\r\nlet x=1;\r\n```\r\n";
        std::fs::write(&path,original).unwrap();
        let (guard,body)=source(path.to_str().unwrap()).unwrap();
        assert_eq!(body,original);verify(&guard).unwrap();
        std::fs::write(&path,"Changed source").unwrap();
        assert!(verify(&guard).unwrap_err().contains("changed since preview"));
        assert_eq!(std::fs::read_to_string(&path).unwrap(),"Changed source");
    }
    #[test]
    fn generated_notices_are_never_imported_into_canonical_prose() {
        let root=tempfile::tempdir().unwrap();let path=root.path().join("export.md");
        std::fs::write(&path,"> Generated from Adashi; do not edit this file directly.\n\n# Body").unwrap();
        assert!(source(path.to_str().unwrap()).unwrap_err().contains("generated Adashi output"));
    }
}

fn source(path: &str) -> Result<(ImportSource, String), String> {
    let path = Path::new(path).canonicalize().map_err(|e| format!("Cannot read source: {e}"))?;
    if !path.extension().is_some_and(|e| e.eq_ignore_ascii_case("md")) { return Err("Select a Markdown (.md) file".into()); }
    let body = std::fs::read_to_string(&path).map_err(|e| format!("Source must be a readable UTF-8 file: {e}"))?;
    if body.trim_start().starts_with("> Generated from Adashi;") || body.trim_start().starts_with("<!-- Generated from Adashi;") || body.trim_start().starts_with("<!-- Generated Adashi agent workflow;") {
        return Err("This is generated Adashi output. Open its canonical document instead of importing the generated notice.".into());
    }
    let fingerprint = format!("{:x}", Sha256::digest(body.as_bytes()));
    Ok((ImportSource { source_path: crate::settings::normalize_project_folder_path(&path), fingerprint }, body))
}

pub(super) fn verify(source_guard: &ImportSource) -> Result<(),String> {
    let (current, _) = source(&source_guard.source_path)?;
    if current.fingerprint != source_guard.fingerprint { return Err("Import source changed since preview. Preview the file again; your draft is retained.".into()); }
    Ok(())
}

#[tauri::command]
pub(super) async fn pick_markdown_import(app: AppHandle) -> Result<Option<String>,String> {
    tauri::async_runtime::spawn_blocking(move || app.dialog().file().set_title("Select Markdown design to import").add_filter("Markdown", &["md"]).blocking_pick_file()
        .map(|p|p.simplified().into_path().map(|p|crate::settings::normalize_project_folder_path(&p)).map_err(|e|e.to_string())).transpose()).await.map_err(|e|e.to_string())?
}

#[tauri::command]
pub(super) async fn preview_markdown_import(state:State<'_,AppState>, project_id:String, source_path:String) -> Result<ImportPreview,String> {
    let project = resolve_project(&state,Some(&project_id))?;
    tauri::async_runtime::spawn_blocking(move || {
        let selected = if Path::new(&source_path).is_absolute() { std::path::PathBuf::from(&source_path) } else { Path::new(&project.folder).join(&source_path) };
        let (source, body) = source(&selected.to_string_lossy())?;
        let title = body.lines().find_map(|l|l.strip_prefix("# ").map(str::trim)).filter(|s|!s.is_empty())
            .map(str::to_owned).unwrap_or_else(||Path::new(&source.source_path).file_stem().unwrap_or_default().to_string_lossy().into_owned());
        let external_id = format!("import-{}",source.fingerprint);
        let mut store = ProjectStore::open(&project).map_err(|e|e.to_string())?;
        let snapshot = store.snapshot().map_err(|e|e.to_string())?;
        let inventory = snapshot.design_inventory().map_err(|e|e.to_string())?;
        let mut duplicates = Vec::new();
        // Explicit import only: inspect full content in bounded batches, never during project open.
        for chunk in inventory.markdown.chunks(100) {
            let ids = chunk.iter().map(|d|format!("markdown:{}",d.external_id)).collect::<Vec<_>>();
            for d in snapshot.design_documents(&ids).map_err(|e|e.to_string())? {
                let document: MarkdownDesignDocument = serde_json::from_value(d.document).map_err(|e|e.to_string())?;
                if document.body == body || document.external_id == external_id { duplicates.push(document.external_id); }
            }
        }
        Ok(ImportPreview {source, document:MarkdownDesignDocument {external_id,title,body,design_links:vec![]},duplicates})
    }).await.map_err(|e|e.to_string())?
}
